version: '2'
services:
    jhi1-app:
        image: jhi1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhi1-mysql:3306/jhi1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhi1-elasticsearch:9300
        ports:
            - 8080:8080
    jhi1-mysql:
        extends:
            file: mysql.yml
            service: jhi1-mysql
    jhi1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhi1-elasticsearch
